---

globals:
  log_level: INFO
functions:
  collect_rss_entries:
    items:
      -
        url: https://ameblo.jp/wakeupgirls/rss.html
        id_prefix: wug
  detect_website_changes:
    items:
      -
        url: https://ameblo.jp/wakeupgirls/rss.html
